---
# tasks file for ansible-role-vim
- name: "Check if indentLine plugin is installed."
  stat:
    path: "{{ vim_home_path }}/.vim/pack/vendor/start/indentLine"
  become: false
  register: identline

- name: "Clone indentLine repo if identLine is not installed."
  git:
    repo: https://github.com/Yggdroot/indentLine.git
    dest: "{{ vim_home_path }}/.vim/pack/vendor/start/indentLine"
  become: false
  when: not identline.stat.exists

- name: "Register identLine plugin if identLine is not installed."
  command: 'vim -u NONE -c "helptags {{ vim_home_path }}/.vim/pack/vendor/start/indentLine/doc" -c "q"'
  become: false
  when: not identline.stat.exists
